/*****************************************************************//**
 * \file   Pc_SGM_OSD.h
 * \brief  Pre-computed SGM in OSD to avoid GE partially, Choi's method
 * 
 * \author 26259
 * \date   March 2024
 *********************************************************************/

#pragma once

#include"OSD.h"

class Pc_SGM_OSD {
protected:
	int n;
	int k;
	int min_Hamming_distance;

	// variables during decoding
	Matrix<int> r_abs_Gs_record;			// Permutation for obtaining MRIPs
	Matrix<GF2> y;						// Hard-decisions of received vector
	Matrix<my_double> r_abs;				// Received vector in absolute value
	Matrix<my_double> r_Gs;			// Permuted received vector
	Matrix<my_double> r_abs_Gs;		// Permuted received vector in absolute value
	Matrix<GF2> Gs;					// Systematic generator matrix corresponding to MRIPs
	Matrix<GF2> Hs;					// Systematic generator matrix corresponding to MRIPs
	Matrix<GF2> y_Gs;					// Permuted hard-decisions of received vector
	Matrix<GF2> c0_Gs;					// First permuted codeword candidate
	Matrix<GF2> cb_Gs;					// The best permuted codeowrd candidate
	my_double w_min;							// Minimum sort Hamming weight that is recorded through re-encoding
	OSD_TEP TEP_generator;				// TEP 'TEP_generator.now' will be generated sequentially
	Matrix<GF2> ce_Gs;					// Permuted codeowrd candidate generated by TEP 'TEP_generator.now'
	my_double w_ce_Gs;						// Sort Hamming weight of 'ce_Gs'
	int error_num;								// Number of different bits between 'y_Gs' and 'ce_Gs' ( 'c0_Gs' when in phase-0 )

	my_double G_threshold;					// threshold for ML criterion
	my_double G_OSD_threshold;				// soft Hamming weight lower bound for OSD phase-i re-processing
	Matrix<my_double> G_threshold_component;	// store r_abs_bar values adding in that constitute G_threshold

	Matrix<int> permutation_first;		// Permutation that ensures decreasing reliability
	Matrix<int> permutation_second;		// Permutation that ensures the Gs systematic on left, disrupts decreasing reliability
	Matrix<int> permutation_all;			// Permutation that combines 'permutation_first' and 'permutation_second'
	Matrix<my_double> r_abs_bar;			// 'r_abs' sorted in REAL decreasing reliability, 'r_abs_Gs' without 'permutation_second'
	Matrix<GF2> y_bar;					// 'y_Gs' without 'permutation_second'
	Matrix<GF2> cb_bar;					// 'cb_Gs' without 'permutation_second'

public:
	Matrix<GF2> G;
	Matrix<GF2> H;
	int order;
	Matrix<GF2> c_hat;					// Optimal codeword for output
	int type;
	bool by_generator;

	// simulation statistics
	int TEP_num;						// number of TEP used for re-encoding
	bool is_early_termination;			// if ture, the decoding is terminated by stopping condition

	// interface
	my_double sigma;					// denote the received signal noise, keep for order-skipping condition
	int ET_type;						// 0 -> no stopping criterion; 1 -> general ML stopping criterion; 
	// 2 -> OSD specific ML stopping criterion; 3 -> OS stopping cirterion

	int num_pre_computed;
	Matrix<Matrix<int>> permutation_pre_computed;
	Matrix<Matrix<GF2>> G_pre_computed;
	Matrix<Matrix<int>> permutation_pre_computed_second;
	int order_pre_computed;
	bool is_GE_skip;


	Pc_SGM_OSD(const Matrix<GF2>& _G, const Matrix<GF2>& _H, int _d, int _order \
	) : TEP_generator(_G.row() <= _H.row() ? _G.row() : _H.col() - _H.row()) {

		by_generator = _G.row() <= _H.row();
		n = by_generator ? _G.col() : _H.col();

		type = 31;
		cout << "Pc_SGM_OSD(" << _order << ")" << endl;

		if (by_generator == true) {
			G = _G;
			k = G.row();
		}
		else {
			H = _H;
			k = n - H.row();
			Gs = Matrix<GF2>(k, n, 'i');
		}

		min_Hamming_distance = _d;
		order = _order;
		r_abs.resize(1, n);
		y.resize(1, n);
		c0_Gs.resize(1, n);
		ce_Gs.resize(1, n);

		// initialize to arbitary values
		w_min = 0;
		w_ce_Gs = 0;
		error_num = 0;
		G_threshold = 0;
		G_OSD_threshold = 0;

		TEP_num = 0;
		is_early_termination = false;

		sigma = 0;				// reset arbitary, need to change with the channel SNR
		ET_type = 3;			// the most efficient and non-significant performance loss ET

		/**
		 * . Take care: the parameter for Pre-computed SGM OSD deocding is set inside the class
		 * \param	num_pre_computed:		number of SGMs pre-computed
		 * \param	order_pre_computed:		order of re-processing for precomputed SGMs
		 */

		// pre-compute 3 SGM for re-encoding, and set 'order_pre_computed' to 1
		num_pre_computed = 3;
		order_pre_computed = 1;

		// set 'permutation_pre_computed' and 'G_pre_computed' by cyclic shift of 'nat' and 'G'
		permutation_pre_computed.resize(1, num_pre_computed);
		G_pre_computed.resize(1, num_pre_computed);
		Matrix<int> nat(1, n, 'N');
		for (int i = 0; i < num_pre_computed; ++i) {
			nat.col_shift_right_cir(n * i / (num_pre_computed), permutation_pre_computed[i]);
			if (by_generator == true) {
				G_pre_computed[i] = G;
				G_pre_computed[i].permute_col(permutation_pre_computed[i]);
				// G.permute_column(permutation_first, Gs);

				G_pre_computed[i].GJE_4_GF2_left(permutation_pre_computed[i]);
				//cout << "Gs" << Gs;
			}
			else {
				Hs = H;
				Hs.permute_col(permutation_pre_computed[i]);

				Hs.GJE_4_GF2_right(permutation_pre_computed[i]);

				// set Gs = [I_k | P^T]
				G_pre_computed[i] = Matrix<GF2>(k, n, 'i');
				for (int q = 0; q < k; ++q) {
					for (int j = k; j < n; ++j) {
						G_pre_computed[i](q, j) = Hs(j - k, q);
					}
				}
				//cout << "Gs" << Gs;
			}
		}

		//cout << "permutation_pre_computed" << permutation_pre_computed;
		//cout << "G_pre_computed" << G_pre_computed;
	}

	bool pre_computed_SGM_decoding(const Matrix<my_double>& r) {

		// use Hamming distance criterion what so ever, to be changed to general ML criterion
		int Hd_stop_criteion = (min_Hamming_distance - 1) / 2;

		for (int i = 0; i < n; ++i) {
			//r_abs[i] = my::abs(r[i]);
			y[i] = r[i] > 0 ? 0 : 1;
		}

		// traverse precomputed SGM
		for (int i = 0; i < num_pre_computed; ++i) {

			Gs = G_pre_computed[i];

			y_Gs = y;
			y_Gs.permute(permutation_pre_computed[i]);


			//c0_Gs = yB_Gs * Gs;
			first_re_encoding();
			//cout << "c0_Gs" << c0_Gs;
			//w_min = soft_Hamming_weight(c0_Gs);
			//cout << "w_min = " << w_min << endl;

			//cout << "my_double_auxiliary_storage::operation_number (2) = " << my_double_auxiliary_storage::operation_number << endl;

			if (c0_Gs.Hamming_distance(y_Gs) < Hd_stop_criteion){

				c_hat = c0_Gs;
				c_hat.permute_back(permutation_pre_computed[i]);
				is_early_termination = true;

				return true;
			}

			// do re-encoding on pre-computed SGM, same to choi's algorithm, but the latter FSD part is replaced by our original OSD
			for (int p = 1; p <= order_pre_computed; ++p) {
				TEP_generator.set_weight(p);

				while (TEP_generator.now[0] >= 0) {

					//cout << "TEP_generator.now" << TEP_generator.now;

					re_encoding(TEP_generator.now);

					//cout << "ce_Gs" << ce_Gs;
					//w_ce_Gs = soft_Hamming_weight(ce_Gs);
					//cout << "w_ce_Gs = " << w_ce_Gs << endl;

					//if (w_ce_Gs < w_min) {
					//	w_min = w_ce_Gs;
					//	cb_Gs = ce_Gs;

					//	if (optimal_termination(i) == true) {
					//		return;
					//	}
					//}

					if (ce_Gs.Hamming_distance(y_Gs) < Hd_stop_criteion) {

						c_hat = ce_Gs;
						c_hat.permute_back(permutation_pre_computed[i]);
						is_early_termination = true;

						return true;
					}

					TEP_generator.next();
				}
			}
		}

		return false;
	}

	void call_GE_only(const Matrix<my_double>& r) {

		//for (int i = 0; i < n; ++i) {
		//	r_abs[i] = my::abs(r[i]);
		//	y[i] = r[i] > 0 ? 0 : 1;
		//}
		//permutation_first = Matrix<int>(1, n, 'N');								// Vector_ext::natual<n>(permutation_first);
		//r_abs_bar = r_abs;
		//r_abs_bar.quick_sort_recur_gt_with_ind(0, n - 1, permutation_first);	// r_abs.sort_gt_with_record(permutation_first, r_abs_bar);
		//y_bar = y;
		//y_bar.permute(permutation_first);										// y.permute(permutation_first, y_bar);
		//Gs = G;
		//Gs.permute_col(permutation_first);
		//// G.permute_column(permutation_first, Gs);
		//permutation_second = Matrix<int>(1, n, 'N'); // Vector_ext::natual<n>(permutation_second);
		//Gs.GJE_4_GF2_left(permutation_second);
		////cout << "Gs" << Gs;

		for (int i = 0; i < n; ++i) {
			r_abs[i] = my::abs(r[i]);
			y[i] = r[i] > 0 ? 0 : 1;
		}
		permutation_first = Matrix<int>(1, n, 'N');								// Vector_ext::natual<n>(permutation_first);
		r_abs_bar = r_abs;
		r_abs_bar.quick_sort_recur_gt_with_ind(0, n - 1, permutation_first);	// r_abs.sort_gt_with_record(permutation_first, r_abs_bar);
		y_bar = y;
		y_bar.permute(permutation_first);										// y.permute(permutation_first, y_bar);

		if (by_generator == true) {
			Gs = G;
			Gs.permute_col(permutation_first);
			// G.permute_column(permutation_first, Gs);

			permutation_second = Matrix<int>(1, n, 'N'); // Vector_ext::natual<n>(permutation_second);
			Gs.GJE_4_GF2_left(permutation_second);
			//cout << "Gs" << Gs;
		}
		else {
			Hs = H;
			Hs.permute_col(permutation_first);

			permutation_second = Matrix<int>(1, n, 'N'); // Vector_ext::natual<n>(permutation_second);
			Hs.GJE_4_GF2_right(permutation_second);

			// set Gs = [I_k | P^T]
			for (int i = 0; i < k; ++i) {
				for (int j = k; j < n; ++j) {
					Gs(i, j) = Hs(j - k, i);
				}
			}
			//cout << "Gs" << Gs;
		}

		permutation_all = permutation_first;
		permutation_all.permute(permutation_second);	// combine the two permutation, forming a permutation to obtain MRIPs
		//cout << "permutation_all" << permutation_all;

		r_Gs = r;
		r_Gs.permute(permutation_all);			// remember this is a new permutation, all vectors should be re-freshed
		r_abs_Gs = r_abs;
		r_abs_Gs.permute(permutation_all);	// absence of this line cause my first problem, mark down here
		y_Gs = y;
		y_Gs.permute(permutation_all);
		//cout << "r_Gs" << r_Gs;
	}

	// the decoding result is 'c_hat', which can be fetched from the class
	void solve(const Matrix<my_double>& r) {

		TEP_num = 0;
		is_early_termination = false;
		is_GE_skip = false;

		if (pre_computed_SGM_decoding(r) == true) {
			is_GE_skip = true;
			return;
		}

		for (int i = 0; i < n; ++i) {
			r_abs[i] = my::abs(r[i]);
			//y[i] = r[i] > 0 ? 0 : 1;
		}
		permutation_first = Matrix<int>(1, n, 'N');								// Vector_ext::natual<n>(permutation_first);
		r_abs_bar = r_abs;
		r_abs_bar.quick_sort_recur_gt_with_ind(0, n - 1, permutation_first);	// r_abs.sort_gt_with_record(permutation_first, r_abs_bar);
		y_bar = y;
		y_bar.permute(permutation_first);										// y.permute(permutation_first, y_bar);

		if (by_generator == true) {
			Gs = G;
			Gs.permute_col(permutation_first);
			// G.permute_column(permutation_first, Gs);

			permutation_second = Matrix<int>(1, n, 'N'); // Vector_ext::natual<n>(permutation_second);
			//Gs.GJE_4_GF2_left(permutation_second);
			
			Gs.GE_left_identity_match_jiabao(permutation_second);

			//cout << "Gs" << Gs;
		}
		else {
			Hs = H;
			Hs.permute_col(permutation_first);

			permutation_second = Matrix<int>(1, n, 'N'); // Vector_ext::natual<n>(permutation_second);
			//Hs.GJE_4_GF2_right(permutation_second);

			Hs.GE_right_identity_match_jiabao(permutation_second);

			// set Gs = [I_k | P^T]
			for (int i = 0; i < k; ++i) {
				for (int j = k; j < n; ++j) {
					Gs(i, j) = Hs(j - k, i);
				}
			}
			//cout << "Gs" << Gs;
		}

		permutation_all = permutation_first;
		permutation_all.permute(permutation_second);	// combine the two permutation, forming a permutation to obtain MRIPs
		//cout << "permutation_all" << permutation_all;

		r_Gs = r;
		r_Gs.permute(permutation_all);			// remember this is a new permutation, all vectors should be re-freshed
		r_abs_Gs = r_abs;
		r_abs_Gs.permute(permutation_all);	// absence of this line cause my first problem, mark down here
		y_Gs = y;
		y_Gs.permute(permutation_all);
		//cout << "r_Gs" << r_Gs;


		//cout << "my_double_auxiliary_storage::operation_number (1) = " << my_double_auxiliary_storage::operation_number << endl;

		//y_Gs.get_part<k>(0, k - 1, yB_Gs);
		//cout << "y_Gs" << y_Gs;
		//cout << "yB_Gs" << yB_Gs;

		//c0_Gs = yB_Gs * Gs;
		first_re_encoding();
		//cout << "c0_Gs" << c0_Gs;
		w_min = soft_Hamming_weight(c0_Gs);
		//cout << "w_min = " << w_min << endl;

		cb_Gs = c0_Gs;
		//cout << "cb_Gs" << cb_Gs;

		//cout << "my_double_auxiliary_storage::operation_number (2) = " << my_double_auxiliary_storage::operation_number << endl;

		if (phase_0_termination() == true) {
			return;
		}

		//cout << "my_double_auxiliary_storage::operation_number (3) = " << my_double_auxiliary_storage::operation_number << endl;

		//cout << "c0_Gs" << c0_Gs;
		//cout << "d_min = " << d_min << endl;

		//cout << "G_threshold_component" << G_threshold_component;
		//cout << "G_threshold = " << G_threshold << endl;


		for (int i = 1; i <= order; ++i) {
			TEP_generator.set_weight(i);

			if (new_order_termination(i) == true) {
				return;
			}


			while (TEP_generator.now[0] >= 0) {

				//cout << "TEP_generator.now" << TEP_generator.now;

				re_encoding(TEP_generator.now);

				//cout << "ce_Gs" << ce_Gs;
				w_ce_Gs = soft_Hamming_weight(ce_Gs);
				//cout << "w_ce_Gs = " << w_ce_Gs << endl;

				if (w_ce_Gs < w_min) {
					w_min = w_ce_Gs;
					cb_Gs = ce_Gs;

					if (optimal_termination(i) == true) {
						return;
					}
				}
				TEP_generator.next();
			}
		}

		//cout << "my_double_auxiliary_storage::operation_number (4) = " << my_double_auxiliary_storage::operation_number << endl;

		//cout << "cb_Gs" << cb_Gs;
		c_hat = cb_Gs;
		c_hat.permute_back(permutation_all);
		return;
	}

	void first_re_encoding() {
		// re-encode 'yB_Gs' into 'c0_Gs', i.e., c0_Gs = yB_Gs * Gs;

		// reset to all-0 vector
		c0_Gs.reset(0);

		for (int j = 0; j < k; ++j) {

			if (y_Gs[j] == 1) {		// consider to write it as 'yB_Gs[j] + 1 == 0' for counting one GF2 operation

				// copy systematic part
				c0_Gs[j] = y_Gs[j];

				// re-encode parity-check part
				int row_start_ind = j * n;
				for (int p = k; p < n; ++p) {
					c0_Gs[p] += Gs[row_start_ind + p];		// add accumulately, this cause my second problem, mark down here
				}
			}

		}

		TEP_num++;
	}

	void re_encoding(const Matrix<int>& TEP_now) {
		// re-encode to ce_Gs

		// initialize ans
		for (int i = 0; i < n; ++i) {
			ce_Gs[i] = c0_Gs[i];
		}

		for (int j = 0; j < TEP_now.size(); ++j) {
			// flip systematic part
			ce_Gs[TEP_now[j]] += 1;

			// re-encode parity-check part
			int row_start_ind = TEP_now[j] * n;
			for (int p = k; p < n; ++p) {
				ce_Gs[p] += Gs[row_start_ind + p];		// add accumulately, this cause my second problem, mark down here
			}
		}

		TEP_num++;
	}

	my_double soft_Hamming_weight(const Matrix<GF2>& c_Gs) {
		my_double ans = 0;
		error_num = 0;
		for (int i = 0; i < n; ++i) {
			if (c_Gs[i] != y_Gs[i]) {
				ans += r_abs_Gs[i];
				error_num++;
			}
		}
		return ans;
	}

	bool check_ML_codeword_general() {
		// Will always check cb_Gs		
		// 'G_threshold(c_Gs,d)' is only needed to compute


		// Only need 'D0_add_size' reliabilities adding up to form the 'G_threshold'
		int D0_add_size = min_Hamming_distance - error_num;

		// This re-arrange the codeword candidate in decreasing reliability. If not, will not guarantee an ML codeword
		cb_bar = cb_Gs;
		cb_bar.permute_back(permutation_second);

		G_threshold = 0;

		for (int i = n - 1; i >= 0 && D0_add_size > 0; --i) {

			if (cb_bar[i] == y_bar[i]) {		// 'D0' set, traverse starting from the least reliable position
				G_threshold += r_abs_bar[i];
				D0_add_size--;

				//if (w_min < G_threshold) return true;		// in align with Guo
			}
		}
		return (w_min < G_threshold);
		//return false;		// ML criterion for general codeword
	}

	bool check_ML_codeword_OSD_specific(int TEP_weight) {
		// Will always check cb_Gs		
		// 'G_threshold(c_Gs,d)' is only needed to compute

		G_threshold = G_OSD_threshold;
		/*for (int i = 0; i < TEP_weight; ++i) {
			G_threshold += r_abs_Gs[k - 1 - i];
		}*/

		// Only need 'D0_add_size' reliabilities adding up to 'G_threshold' further form the entire 'G_threshold'
		int D0_add_size = min_Hamming_distance - error_num - TEP_weight;

		// This re-arrange the codeword candidate in decreasing reliability. If not, will not guarantee an ML codeword
		cb_bar = cb_Gs;
		cb_bar.permute_back(permutation_second);

		G_threshold_component.clear();

		for (int i = n - 1; i >= 0 && D0_add_size > 0; --i) {

			if (cb_bar[i] == y_bar[i]) {		// 'D0' set, traverse starting from the least reliable position
				G_threshold += r_abs_bar[i];
				D0_add_size--;

				//if (w_min < G_threshold) return true;		// in align with Guo
				G_threshold_component.push_back(r_abs_bar[i]);
			}
		}
		return (w_min < G_threshold);
		//return false;		// ML criterion for general codeword
	}

	bool check_ML_codeword_OSD_new_phase(int phase_num) {

		//cout << "r_abs_Gs" << r_abs_Gs;
		//cout << "r_abs_Gs[k - phase_num] = " << r_abs_Gs[k - phase_num] << endl;

		// update 'G_threshold' for a new judgement
		if (!G_threshold_component.empty()) {

			G_threshold += r_abs_Gs[k - phase_num] - G_threshold_component.back();
			G_threshold_component.pop_back();
		}
		else {
			G_threshold += r_abs_Gs[k - phase_num];
		}

		// judge the current best codeword if it is ML
		if (w_min < G_threshold) {
			return true;
		}
		else {
			// update 'G_OSD_threshold' for the following codeword candidates
			G_OSD_threshold += r_abs_Gs[k - phase_num];
			return false;
		}
	}

	void G_threshold_OS_OSD_ini() {
		G_threshold = 0;

		my_double scale_by_sigma = 2 / (sigma * sigma);
		for (int i = k; i < n; ++i) {
			G_threshold += r_abs_Gs(i) / (1 + exp(scale_by_sigma * r_abs_Gs(i)));
		}
	}

	void G_threshold_OS_OSD_increase(int phase_num) {
		G_threshold += r_abs_Gs(k - phase_num);
	}

	bool check_codeword_OS_OSD() {
		// Will always check cb_Gs		

		return w_min < G_threshold;
	}

	void early_termination() {
		c_hat = cb_Gs;
		c_hat.permute_back(permutation_all);
		is_early_termination = true;
		return;
	}

	bool phase_0_termination() {
		if (ET_type == 1) {
			if (check_ML_codeword_general() == true) {		// in order-0, this is the same as the OSD specific type			
				early_termination();
				return true;
			}
		}
		else if (ET_type == 2) {
			G_OSD_threshold = 0;

			if (check_ML_codeword_OSD_specific(0) == true) {		// in order-0, this is the same as the OSD specific type			
				early_termination();
				return true;
			}
		}
		else if (ET_type == 3) {

			G_threshold_OS_OSD_ini();
			if (check_codeword_OS_OSD() == true) {		// use order-skipping ET in order-0				
				early_termination();
				return true;
			}
		}
		return false;
	}

	bool new_order_termination(int i) {
		if (ET_type == 2) {
			if (check_ML_codeword_OSD_new_phase(i) == true) {
				early_termination();
				//cout << "my_double_auxiliary_storage::operation_number (4) = " << my_double_auxiliary_storage::operation_number << endl;
				//cout << "GF2e_auxiliary_storage::operation_number (4) = " << GF2e_auxiliary_storage::operation_number << endl;
				return true;
			}
		}
		else if (ET_type == 3) {
			G_threshold_OS_OSD_increase(i);
			if (check_codeword_OS_OSD() == true) {
				early_termination();
				//cout << "my_double_auxiliary_storage::operation_number (4) = " << my_double_auxiliary_storage::operation_number << endl;
				//cout << "GF2e_auxiliary_storage::operation_number (4) = " << GF2e_auxiliary_storage::operation_number << endl;
				return true;
			}
		}
		return false;
	}

	bool optimal_termination(int i) {
		if (ET_type == 1) {
			if (check_ML_codeword_general() == true) {
				early_termination();
				return true;
			}
		}
		else if (ET_type == 2) {
			if (check_ML_codeword_OSD_specific(i) == true) {		// it actually is an ML criterion even for LLOSD		
				early_termination();
				//cout << "my_double_auxiliary_storage::operation_number (4) = " << my_double_auxiliary_storage::operation_number << endl;
				//cout << "GF2e_auxiliary_storage::operation_number (4) = " << GF2e_auxiliary_storage::operation_number << endl;
				return true;
			}
		}
		else if (ET_type == 3) {
			if (check_codeword_OS_OSD() == true) {
				early_termination();
				//cout << "my_double_auxiliary_storage::operation_number (4) = " << my_double_auxiliary_storage::operation_number << endl;
				//cout << "GF2e_auxiliary_storage::operation_number (4) = " << GF2e_auxiliary_storage::operation_number << endl;
				return true;
			}
		}
		return false;
	}
};